SELECT
    OBS_ID,
    COUNTRY_ID,
    INDICATOR_ID,
    PERIOD_START,
    YEAR,
    VALUE,
    TRIM(SOURCE_SYSTEM) AS SOURCE_SYSTEM,
    VINTAGE_DATE,
    IS_ESTIMATE,
    UPDATED_AT
FROM {{ source('gdp_raw', 'RAW_OBSERVATIONS') }}