SELECT
    INDICATOR_ID,
    TRIM(INDICATOR_CODE) AS INDICATOR_CODE,
    TRIM(INDICATOR_NAME) AS INDICATOR_NAME,
    TRIM(UNIT) AS UNIT,
    TRIM(FREQUENCY) AS FREQUENCY,
    TRIM(DESCRIPTION) AS DESCRIPTION
FROM {{ source('gdp_raw', 'RAW_INDICATORS') }}