SELECT
    FX_ID,
    COUNTRY_ID,
    UPPER(TRIM(BASE_CCY)) AS BASE_CCY,
    UPPER(TRIM(QUOTE_CCY)) AS QUOTE_CCY,
    AS_OF_DATE,
    FX_RATE_BASE_PER_QUOTE,
    TRIM(SOURCE_SYSTEM) AS SOURCE_SYSTEM,
    UPDATED_AT
FROM {{ source('gdp_raw', 'RAW_FX_RATES') }}