SELECT
    COUNTRY_ID,
    TRIM(COUNTRY_NAME) AS COUNTRY_NAME,
    UPPER(TRIM(ISO3)) AS ISO3,
    TRIM(CONTINENT) AS CONTINENT,
    TRIM(SUB_REGION) AS SUB_REGION,
    UPPER(TRIM(LOCAL_CURRENCY)) AS LOCAL_CURRENCY,
    TRIM(MARKET_TYPE) AS MARKET_TYPE,
    TRIM(INCOME_GROUP) AS INCOME_GROUP,
    MEMBER_SINCE,
    UPDATED_AT
FROM {{ source('gdp_raw', 'RAW_COUNTRIES') }}